add_newline = false
format = """$directory$character"""
right_format = """$all"""

# Replace the "❯" symbol in the prompt with "❯❯"
[character]
format = "$symbol "
success_symbol = "[➜](bold white)"
error_symbol = "[➜](bold red)"

[status]
disabled = false
map_symbol = true
format='exit code [$status]($style)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Disable the AWS module.
[aws]
disabled = true

[battery]
disabled=true

# Set the time format
[time]
disabled = false

[helm]
disabled=true

# Directory setttings
[directory]
format = " [$path]($style)[$read_only]($read_only_style) "
truncation_length = -1
style = "#CD435E bold"
truncate_to_repo = true

[username]
style_user = "#4E9CB0 bold"
style_root = "#792167 bold"
format = "  [$user]($style) "
disabled = true
show_always = true

[hostname]
ssh_only = true
format = "at [$hostname](#225663 bold) "
disabled = false

[cmd_duration]
min_time = 100
format = "underwent [$duration](dimmed #5DD5AE) "

[git_status]
disabled = false
style = '#e28743'

[git_branch]
symbol = " "
style = "#e28743"
#truncation_length = 15

[terraform]
disabled = true

[python]
disabled=true

[golang]
disabled=true

[docker_context]
disabled=true
