// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package sdd

import (
	"fmt"

	"github.com/cockroachdb/errors"
)

const (
	// EventKindUnknown is a eventKind of type Unknown.
	EventKindUnknown eventKind = iota
	// EventKindInit is a eventKind of type Init.
	EventKindInit
	// EventKindAssistantText is a eventKind of type AssistantText.
	EventKindAssistantText
	// EventKindToolUse is a eventKind of type ToolUse.
	EventKindToolUse
	// EventKindToolResult is a eventKind of type ToolResult.
	EventKindToolResult
	// EventKindResult is a eventKind of type Result.
	EventKindResult
)

var ErrInvalideventKind = errors.New("not a valid eventKind")

const _eventKindName = "unknowninitassistantTexttoolUsetoolResultresult"

var _eventKindMap = map[eventKind]string{
	EventKindUnknown:       _eventKindName[0:7],
	EventKindInit:          _eventKindName[7:11],
	EventKindAssistantText: _eventKindName[11:24],
	EventKindToolUse:       _eventKindName[24:31],
	EventKindToolResult:    _eventKindName[31:41],
	EventKindResult:        _eventKindName[41:47],
}

// String implements the Stringer interface.
func (x eventKind) String() string {
	if str, ok := _eventKindMap[x]; ok {
		return str
	}
	return fmt.Sprintf("eventKind(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x eventKind) IsValid() bool {
	_, ok := _eventKindMap[x]
	return ok
}

var _eventKindValue = map[string]eventKind{
	_eventKindName[0:7]:   EventKindUnknown,
	_eventKindName[7:11]:  EventKindInit,
	_eventKindName[11:24]: EventKindAssistantText,
	_eventKindName[24:31]: EventKindToolUse,
	_eventKindName[31:41]: EventKindToolResult,
	_eventKindName[41:47]: EventKindResult,
}

// ParseeventKind attempts to convert a string to a eventKind.
func ParseeventKind(name string) (eventKind, error) {
	if x, ok := _eventKindValue[name]; ok {
		return x, nil
	}
	return eventKind(0), fmt.Errorf("%s is %w", name, ErrInvalideventKind)
}
