user www-data;
worker_processes auto;

pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;

    server {
        listen 80;
        server_name teadove.space;

        return 301 https://teadove.space:7999$request_uri;
    }

    server {
        listen 7999 ssl;
        server_name teadove.space;

        ssl_certificate     /etc/letsencrypt/live/teadove.space/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/teadove.space/privkey.pem;

        # OpenAI API
        #
        # https://teadove.space:7999/proxy/openai/v1/responses
        # ->
        # https://api.openai.com/v1/responses
        location /proxy/openai/ {
            proxy_pass https://api.openai.com/;

            proxy_ssl_server_name on;
            proxy_ssl_name api.openai.com;

            proxy_set_header Host api.openai.com;
            proxy_http_version 1.1;

            proxy_buffering off;
            proxy_request_buffering off;

            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }

        # Telegram Bot API
        #
        # https://teadove.space:7999/proxy/telegram-bot/<TOKEN>/sendMessage
        # ->
        # https://api.telegram.org/bot<TOKEN>/sendMessage
        location /proxy/telegram-bot/ {
            proxy_pass https://api.telegram.org/bot;

            proxy_ssl_server_name on;
            proxy_ssl_name api.telegram.org;

            proxy_set_header Host api.telegram.org;
            proxy_http_version 1.1;

            proxy_buffering off;
            proxy_request_buffering off;

            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
        }

        location / {
            return 404;
        }
    }
}
